package itu.dd.client.tech.exception;

import android.util.AndroidException;

public class RESTFacadeException extends AndroidException {
	protected String msg;
	protected String LOGTAG;
	
	public RESTFacadeException(String LOGTAG, String msg){
		super(LOGTAG + ": "+ msg);
		this.LOGTAG = LOGTAG;
		this.msg = msg;
	}
	
	public RESTFacadeException(String LOGTAG, String msg, Exception cause){
		super(cause);
		this.LOGTAG = LOGTAG;
		this.msg = msg;
	}
	
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = 3286908339345443817L;
	

}
