package itu.malta.drunkendroid.tech.exception;

import android.util.AndroidException;

public class RESTFacadeException extends AndroidException {

	public RESTFacadeException(String LOGTAG, String msg){
		super(LOGTAG + ": "+ msg);
	}
	
	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = 3286908339345443817L;
	

}
